# Generated by Django 4.2.26 on 2025-11-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
