# Generated by Django 4.2.26 on 2025-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchase_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='birthday',
            field=models.DateField(),
        ),
    ]
